/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciointerfacest2;
import java.util.*;
public class BibliotecaSteam extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecaSteam
     */
    public BibliotecaSteam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aniadir = new javax.swing.JPanel();
        aniadirjuego = new javax.swing.JButton();
        galeria = new javax.swing.JPanel();
        game1 = new javax.swing.JToggleButton();
        game2 = new javax.swing.JButton();
        game3 = new javax.swing.JButton();
        game4 = new javax.swing.JButton();
        game5 = new javax.swing.JButton();
        game6 = new javax.swing.JButton();
        game7 = new javax.swing.JButton();
        game8 = new javax.swing.JButton();
        game9 = new javax.swing.JButton();
        game10 = new javax.swing.JButton();
        game11 = new javax.swing.JButton();
        game12 = new javax.swing.JButton();
        Interfazusuario = new javax.swing.JPanel();
        NombreUsuario = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cuenta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aniadir.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        aniadirjuego.setText("Añadir Un juego ");
        aniadirjuego.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aniadirjuego.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        aniadir.add(aniadirjuego);

        getContentPane().add(aniadir, java.awt.BorderLayout.SOUTH);

        galeria.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        galeria.setLayout(new java.awt.GridLayout(3, 4, 30, 20));
        galeria.add(game1);
        galeria.add(game2);
        galeria.add(game3);
        galeria.add(game4);
        galeria.add(game5);
        galeria.add(game6);
        galeria.add(game7);
        galeria.add(game8);
        galeria.add(game9);
        galeria.add(game10);
        galeria.add(game11);
        galeria.add(game12);

        getContentPane().add(galeria, java.awt.BorderLayout.CENTER);

        Interfazusuario.setName(""); // NOI18N
        Interfazusuario.setLayout(new java.awt.GridLayout(1, 1));

        NombreUsuario.setLayout(new java.awt.GridLayout(2, 2));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("username");
        nombre.setFocusable(false);
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NombreUsuario.add(nombre);
        NombreUsuario.add(jLabel2);
        NombreUsuario.add(jLabel1);
        NombreUsuario.add(jLabel4);

        Interfazusuario.add(NombreUsuario);

        javax.swing.GroupLayout CuentaLayout = new javax.swing.GroupLayout(Cuenta);
        Cuenta.setLayout(CuentaLayout);
        CuentaLayout.setHorizontalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        CuentaLayout.setVerticalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        Interfazusuario.add(Cuenta);

        getContentPane().add(Interfazusuario, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        HashMap<String, Juego> biblioteca = new HashMap<String, Juego>();
        Juego Cyberpunk2077 = new Juego("Cyberpunk2077","","CDProject","Ciencia Ficción",2020);
        System.out.println(Cyberpunk2077.isJugando());
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaSteam().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuenta;
    private javax.swing.JPanel Interfazusuario;
    private javax.swing.JPanel NombreUsuario;
    private javax.swing.JPanel aniadir;
    private javax.swing.JButton aniadirjuego;
    private javax.swing.JPanel galeria;
    private javax.swing.JToggleButton game1;
    private javax.swing.JButton game10;
    private javax.swing.JButton game11;
    private javax.swing.JButton game12;
    private javax.swing.JButton game2;
    private javax.swing.JButton game3;
    private javax.swing.JButton game4;
    private javax.swing.JButton game5;
    private javax.swing.JButton game6;
    private javax.swing.JButton game7;
    private javax.swing.JButton game8;
    private javax.swing.JButton game9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
