/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciointerfacest2;

import java.util.HashMap;

/**
 *
 * @author Guillermo
 */
public class Steam_biblioteca extends javax.swing.JFrame {
public static HashMap<String, Juego> biblioteca = new HashMap<String, Juego>();
    /**
     * Creates new form Steam_biblioteca
     */
    public Steam_biblioteca() {
        initComponents();
        
        Juego Cyberpunk2077 = new Juego("Cyberpunk2077","","CDProject","Ciencia Ficción",2020);
        Juego SuperMarioBross = new Juego("SuperMarioBross","","Nintendo","Plataforma",1985);
        Juego RainWorld = new Juego("RainWorld","","VideoKult","Mundo abierto 2D",2017);
        Juego TheBindingOfIsaacRepetence = new Juego("TheBindingOfIsaacRepetence","","	Edmund McMillen","Disparos Rol y Acción",2021);
        biblioteca.put(Cyberpunk2077.getNombrejuego(),Cyberpunk2077);
        biblioteca.put(SuperMarioBross.getNombrejuego(),SuperMarioBross);
        biblioteca.put(RainWorld.getNombrejuego(),RainWorld);
        biblioteca.put(TheBindingOfIsaacRepetence.getNombrejuego(),TheBindingOfIsaacRepetence);
        
        game1.setText(biblioteca.get(Cyberpunk2077.getNombrejuego()).getNombrejuego());
        game2.setText(biblioteca.get(SuperMarioBross.getNombrejuego()).getNombrejuego());
        game3.setText(biblioteca.get(RainWorld.getNombrejuego()).getNombrejuego());
        game4.setText(biblioteca.get(TheBindingOfIsaacRepetence.getNombrejuego()).getNombrejuego());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interfazusuario = new javax.swing.JPanel();
        NombreUsuario = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cuenta = new javax.swing.JPanel();
        galeria = new javax.swing.JPanel();
        game1 = new javax.swing.JToggleButton();
        game2 = new javax.swing.JButton();
        game3 = new javax.swing.JButton();
        game4 = new javax.swing.JButton();
        game5 = new javax.swing.JButton();
        game6 = new javax.swing.JButton();
        game7 = new javax.swing.JButton();
        game8 = new javax.swing.JButton();
        game9 = new javax.swing.JButton();
        game10 = new javax.swing.JButton();
        game11 = new javax.swing.JButton();
        game12 = new javax.swing.JButton();
        aniadir = new javax.swing.JPanel();
        aniadirjuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(721, 543));

        Interfazusuario.setName(""); // NOI18N
        Interfazusuario.setLayout(new java.awt.GridLayout(1, 1));

        NombreUsuario.setLayout(new java.awt.GridLayout(2, 2));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("username");
        nombre.setFocusable(false);
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NombreUsuario.add(nombre);
        NombreUsuario.add(jLabel2);
        NombreUsuario.add(jLabel1);
        NombreUsuario.add(jLabel4);

        Interfazusuario.add(NombreUsuario);

        javax.swing.GroupLayout CuentaLayout = new javax.swing.GroupLayout(Cuenta);
        Cuenta.setLayout(CuentaLayout);
        CuentaLayout.setHorizontalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        CuentaLayout.setVerticalGroup(
            CuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        Interfazusuario.add(Cuenta);

        getContentPane().add(Interfazusuario, java.awt.BorderLayout.NORTH);

        galeria.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        galeria.setLayout(new java.awt.GridLayout(3, 4, 30, 20));

        game1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game1ActionPerformed(evt);
            }
        });
        galeria.add(game1);

        game2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game2ActionPerformed(evt);
            }
        });
        galeria.add(game2);

        game3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game3ActionPerformed(evt);
            }
        });
        galeria.add(game3);

        game4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game4ActionPerformed(evt);
            }
        });
        galeria.add(game4);

        game5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game5ActionPerformed(evt);
            }
        });
        galeria.add(game5);

        game6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game6ActionPerformed(evt);
            }
        });
        galeria.add(game6);

        game7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game7ActionPerformed(evt);
            }
        });
        galeria.add(game7);

        game8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game8ActionPerformed(evt);
            }
        });
        galeria.add(game8);

        game9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game9ActionPerformed(evt);
            }
        });
        galeria.add(game9);

        game10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game10ActionPerformed(evt);
            }
        });
        galeria.add(game10);

        game11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game11ActionPerformed(evt);
            }
        });
        galeria.add(game11);

        game12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game12ActionPerformed(evt);
            }
        });
        galeria.add(game12);

        getContentPane().add(galeria, java.awt.BorderLayout.CENTER);

        aniadir.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        aniadirjuego.setText("Añadir Un juego ");
        aniadirjuego.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aniadirjuego.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        aniadirjuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirjuegoActionPerformed(evt);
            }
        });
        aniadir.add(aniadirjuego);

        getContentPane().add(aniadir, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void game1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game1ActionPerformed
        
        if(game1.getText()==null || game1.getText().equals("")){
        
        }
        else{
        Juego game1j = biblioteca.get(game1.getText());
        lanzarjuego(game1j);
        }
        
        
    }//GEN-LAST:event_game1ActionPerformed

    private void aniadirjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirjuegoActionPerformed
      
       aniadirjuegos frame = new aniadirjuegos();
       frame.setVisible(true);
       
    }//GEN-LAST:event_aniadirjuegoActionPerformed

    private void game2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game2ActionPerformed
       if(game2.getText()==null || game2.getText().equals("")){
        
        }
        else{
        Juego game2j = biblioteca.get(game2.getText());
        lanzarjuego(game2j);
        }
    }//GEN-LAST:event_game2ActionPerformed

    private void game3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game3ActionPerformed
          if(game3.getText()==null || game3.getText().equals("")){
          
          }
          else{
          Juego game3j = biblioteca.get(game3.getText());
          lanzarjuego(game3j);
          }
    }//GEN-LAST:event_game3ActionPerformed

    private void game4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game4ActionPerformed
        if(game4.getText()==null || game4.getText().equals("")){
          
          }
        else{
          Juego game4j = biblioteca.get(game4.getText());
          lanzarjuego(game4j);
          }
    }//GEN-LAST:event_game4ActionPerformed

    private void game5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game5ActionPerformed
        if(game5.getText()==null || game5.getText().equals("")){
          
          }
        else{
          Juego game5j = biblioteca.get(game5.getText());
          lanzarjuego(game5j);
          }
    }//GEN-LAST:event_game5ActionPerformed

    private void game6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game6ActionPerformed
        if(game6.getText()==null || game6.getText().equals("")){
          
          }
        else{
          Juego game6j = biblioteca.get(game6.getText());
          lanzarjuego(game6j);
          }
    }//GEN-LAST:event_game6ActionPerformed

    private void game7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game7ActionPerformed
        if(game7.getText()==null || game7.getText().equals("")){
          
          }
        else{
          Juego game7j = biblioteca.get(game7.getText());
          lanzarjuego(game7j);
          }
    }//GEN-LAST:event_game7ActionPerformed

    private void game8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game8ActionPerformed
        if(game8.getText()==null || game8.getText().equals("")){
          
          }
        else{
          Juego game8j = biblioteca.get(game8.getText());
          lanzarjuego(game8j);
          }
    }//GEN-LAST:event_game8ActionPerformed

    private void game9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game9ActionPerformed
        if(game9.getText()==null || game9.getText().equals("")){
          
          }
        else{
          Juego game9j = biblioteca.get(game9.getText());
          lanzarjuego(game9j);
          }
    }//GEN-LAST:event_game9ActionPerformed

    private void game10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game10ActionPerformed
        if(game10.getText()==null || game10.getText().equals("")){
          
          }
        else{
          Juego game10j = biblioteca.get(game10.getText());
          lanzarjuego(game10j);
          }
    }//GEN-LAST:event_game10ActionPerformed

    private void game11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game11ActionPerformed
        if(game11.getText()==null || game11.getText().equals("")){
          
          }
        else{
          Juego game11j = biblioteca.get(game11.getText());
          lanzarjuego(game11j);
          }
    }//GEN-LAST:event_game11ActionPerformed

    private void game12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game12ActionPerformed
        if(game12.getText()==null || game12.getText().equals("")){
          
          }
        else{
          Juego game12j = biblioteca.get(game12.getText());
          lanzarjuego(game12j);
          }
    }//GEN-LAST:event_game12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Steam_biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Steam_biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Steam_biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Steam_biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Steam_biblioteca().setVisible(true);
            }
        });
    }
    
    
    
    
    public static void lanzarjuego(Juego j){
    
       verjuego frame = new verjuego(j);
       frame.setVisible(true);
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuenta;
    private javax.swing.JPanel Interfazusuario;
    private javax.swing.JPanel NombreUsuario;
    private javax.swing.JPanel aniadir;
    private javax.swing.JButton aniadirjuego;
    private javax.swing.JPanel galeria;
    private javax.swing.JToggleButton game1;
    private javax.swing.JButton game10;
    private javax.swing.JButton game11;
    private javax.swing.JButton game12;
    private javax.swing.JButton game2;
    private javax.swing.JButton game3;
    private javax.swing.JButton game4;
    private javax.swing.JButton game5;
    private javax.swing.JButton game6;
    private javax.swing.JButton game7;
    private javax.swing.JButton game8;
    private javax.swing.JButton game9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
