/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciointerfacest2;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Guillermo
 */
public class verjuego extends javax.swing.JFrame {
    private Juego juego;
    /**
     * Creates new form aniadirjuego
     */
    public verjuego() {
        initComponents();
       
    }
    
    public verjuego(Juego juego) {
        initComponents();
        this.juego = juego;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nombrejuego.setText(juego.getNombrejuego());
        nombrecredor.setText(juego.getAutor());
        tematica.setText(juego.getGenero());
        fecha.setText(juego.getPublicacion()+"");
        System.out.println(juego.getPublicacion());
       ImageIcon icono = new ImageIcon(getClass().getResource(juego.getImagen()));
       imagenjuego.setIcon(icono);
        System.out.println(juego.getImagen());
        if(juego.isJugando()){
            juego.setJugando(true);
            jugado.setSelected(true);
        }
        else{
        jugado.setSelected(false);
        }
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        imagenjuego = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombrejuego = new javax.swing.JLabel();
        nombrecredor = new javax.swing.JLabel();
        tematica = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jugado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visor de juegos");
        setMinimumSize(new java.awt.Dimension(475, 632));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        imagenjuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(imagenjuego);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        nombrejuego.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nombrejuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrejuego.setText("a");
        nombrejuego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(nombrejuego);

        nombrecredor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nombrecredor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrecredor.setText("a");
        jPanel2.add(nombrecredor);
        nombrecredor.getAccessibleContext().setAccessibleName("a");

        tematica.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tematica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tematica.setText("a");
        jPanel2.add(tematica);

        fecha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("a");
        jPanel2.add(fecha);

        jPanel1.add(jPanel2);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jugado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jugado.setText("Jugado");
        jugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadoActionPerformed(evt);
            }
        });
        getContentPane().add(jugado, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadoActionPerformed
        if(jugado.isSelected()){
        juego.setJugando(true);
        }
        else{
        juego.setJugando(false);
        }
        
    }//GEN-LAST:event_jugadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verjuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel imagenjuego;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox jugado;
    private javax.swing.JLabel nombrecredor;
    private javax.swing.JLabel nombrejuego;
    private javax.swing.JLabel tematica;
    // End of variables declaration//GEN-END:variables
}
